export const AppImages = {
    // SplashBackground: require(`../assets/Images/SplashScreen.png`),
    logo: require('../assets/Images/VakeelLogo.png'),
    onBoarding1: require('../assets/Images/Onboarding1.png'),
    onBoarding2: require('../assets/Images/Onboarding2.png'),
    onBoarding3: require('../assets/Images/Onboarding3.png'),
    Continue_As: require('../assets/Images/ContinueAs.png'),
    Login_Bg: require('../assets/Images/LoginBg.png'),
    VakeelLogoWithoutName: require('../assets/Images/VakeelLogoWithoutName.png'),
    Notification_Icon: require('../assets/Images/NotificationIcon.png'),
    Cases_Management: require('../assets/Images/CasesManagement.png'),
    Diary_Management: require('../assets/Images/DiaryManagement.png'),
    Team_Management: require('../assets/Images/TeamManagement.png'),
    Home_Icon: require('../assets/Images/HomeIcon.png'),
    Post_Matter: require('../assets/Images/PostMatter.png'),
    My_Matters: require('../assets/Images/MyMatters.png'),
    Success_BG: require('../assets/Images/SuccessBG.png'),
    Judicial_Icon: require('../assets/Images/JudicialIcon.png'),
    NonJudicial_Icone: require('../assets/Images/NonJudicialIcone.png'),
    Criminal_Icon: require('../assets/Images/CriminalIcon.png'),
}